### ISSUE TITLE
FgFlex: attention based subtasks architecture

### ISSUE THREAD

**Issue by pmhalvor** [pmhalvor/fgsa#23]
Using findings from RACL and IMN architectures, build a flexible attention architecture 

- [x] attention between tasks
- [x]  able to train single tasks at a time
- [ ] L2 normalization before attention
- [x] configure layers of cnns per subtask (like IMN)
- [x] sort out what queries, keys, and values are in each of the attentions
- [x] hyper search
